version: "3.9"
services:
  web:
    build:
      context: .
      args:
        GIT_SHA: ${GIT_SHA:-dev}
    image: ${DOCKERHUB_USERNAME:-youruser}/hello-flask:${GIT_SHA:-dev}
    ports:
      - "8000:8000"
    environment:
      - GIT_SHA=${GIT_SHA:-dev}
    restart: unless-stopped

